apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://rancher.my.org/k8s/clusters/local"
    api-version: v1
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akNDQ\
      WRhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFvTVJJd0VBWURWUVFLRXdsMGFHVXQKY\
      21GdVkyZ3hFakFRQmdOVkJBTVRDV05oZEhSc1pTMWpZVEFlRncweE9UQXlNamd3TkRBM05EQmFGd\
      zB5T1RBeQpNalV3TkRBM05EQmFNQ2d4RWpBUUJnTlZCQW9UQ1hSb1pTMXlZVzVqYURFU01CQUdBM\
      VVFQXhNSlkyRjBkR3hsCkxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ\
      0tDQVFFQXZtUjlRZEl0QWFrekRWWDcKYVNwT29SNFZqNE55OXpnbzVBazBQaUFNYkszUW1BcXBaS\
      GE5VXFkL1NvRkMxb3c0NWw3MnBJYkE3ODE2dWkwRwpFSCsvVTV1Q1ZITEhoL25qN1N4TWJPa3pKd\
      UdoaVdSNkZsSkdQZTB2bkM1NC9VdFdQUDFGSklITXJFY2o1MFY4Cng0S21Fam5qelMwVU5lVCt5T\
      Stobm9WZEgrYWNLdlpZQS95NzlHQWlZQkR3TjRZeDAybnQvZlVXREJ0VVlxVUUKZTRsc25xdWdCM\
      DF0NnJNaEVURHBPcmg1Zm02dHh3OVNOSGpOR3gvK1RHWVZNc1FBVEFXMHlWMFcxWGRYN0dqYQp3N\
      jdUM0Q2VzZVc2ZVTGNTSUpLNWJpSFVoMmNYZWs2Rmh3TGgrdmFJbWk3Mnc3UVF6bDJOQnVuYW5Fc\
      GFKSTAvCnNGM3hNd0lEQVFBQm95TXdJVEFPQmdOVkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRS\
      C9CQVV3QXdFQi96QU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbzlDN0hwQlZZc2I4OERlUXAwT\
      nZNc2VuU3VuUTdZd2pvNTFxZlVGSQpVcitzK2dDVHRnaVlEWFBwNkVSbWFMV3ljQXNjUlNsSFNsb\
      WcwUjUvSTN6WFRrelViSkNlSng1Rkk0elA3ZzhICnd1alVjaVpSK3F2STBaSFIrdC9sVVExSzZiR\
      URXRjk3S0xyZWZFOVBZK2llMVFZRE9ZMTkzcUFGenBXSkQwVzkKKzZ4NmJGSmxOK0RuaU9ZbmtXS\
      jZDdWZyZklVRXEvczFIR3ZxbDFiclowdVdHdHpxbi9DNXVuRDlBMUhLYUtqZApXdTFES0czZ2lua\
      002MVAzZUxLeUNPYUh1b2txcFVCUTVubW83aEhGTS9PNmFoZm5LKzFYOFJWV0gxN3oxTk9HCml1N\
      HpQRzVZN2hsZmZJaUtLZmFyME9ueUEyQnp5cnFud1FoZE9FdXdWekNhUXc9PQotLS0tLUVORCBDR\
      VJUSUZJQ0FURS0tLS0t"

users:
- name: "user-4lb4g"
  user:
    token: "kubeconfig-user-4lb4g:bn4zmlfnp6l6h4mvrj5klw4j29h9wcnfn8c2h4s2876cq5j2p7sq2r"

contexts:
- name: "local"
  context:
    user: "user-4lb4g"
    cluster: "local"

current-context: "local"
